spring:
  application:
    name: ecms-sever
  profiles:
    active: 101
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

server:
  tomcat:
    max-swallow-size: 512MB
