#本地测试环境   7008
server:
  port: 18989
spring:
  datasource:
    #url: jdbc:p6spy:mysql://localhost:3306/ecms_servera?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/ecms_servera?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: xxxxxx
    #driverClassName: com.p6spy.engine.spy.P6SpyDriver
    driverClassName: com.mysql.cj.jdbc.Driver

    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP

      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

  liquibase:
    change-log: classpath:/db/changelog/master.xml


mybatis-plus:
  configuration:
    　log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/eicas/cms/mapper/xml/*.xml

filePath:
#  image: /home/eportal/ecms/img/
  image: d:/upload/
#  image: /upload/
  imageMappingPath: /images/
  phantomjs: /usr/local/bin/phantomjs
  loadPath: http://172.20.58.20:18989/images/

column:
  columnId: 1511874398533210113
  notyfyColumnId: 1511874625658945540
swagger3:
  enable: true

oauth:
  server: http://172.20.58.101:9100
  webUrl: http://localhost:8080/ecms-mgt
  clientId: ecms-mgt
  clientSecret: ecms-mgt

