server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecms_server_new?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: jsq123456
    driverClassName: com.mysql.cj.jdbc.Driver
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
mybatis-plus:
  configuration:
    　log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ecms:
  store-root-path: /Users/jsq/Desktop/test
  mapping-root-path: /file
  phantomJS: /usr/local/bin/phantomjs
  upload: /Users/jsq/Desktop/test
  filePrefix: http://localhost:8000/file

ueditor:
  configPath: /Users/jsq/work/code/中科/科大/ecms/config.json

swagger3:
  enable: true


